export const SEO_LANDING_PAGES = [
  {
    slug: "체험단",
    title: "체험단 캠페인 모아보기",
    description: "전국 체험단 캠페인을 지역, 카테고리, 마감일, 제공내역 기준으로 비교해보세요.",
    h1: "전국 체험단 캠페인 모아보기",
    intro: "여러 체험단 플랫폼의 공개 모집글을 한 곳에서 확인하고, 조건에 맞는 캠페인을 빠르게 찾을 수 있습니다.",
    filters: {},
    appQuery: "?tab=explore",
    relatedSlugs: ["맛집체험단", "블로그체험단", "오늘마감-체험단"],
  },
  {
    slug: "블로그체험단",
    title: "블로그 체험단 모집 모아보기",
    description: "블로그 리뷰어를 모집하는 체험단 캠페인을 지역과 마감일 기준으로 찾아보세요.",
    h1: "블로그 체험단 모집 모아보기",
    intro: "블로그 리뷰 작성이 필요한 캠페인을 중심으로 최신 모집글을 정리합니다.",
    filters: { channelKeywords: ["블로그"] },
    appQuery: "?tab=explore&preset=blog",
    relatedSlugs: ["체험단", "맛집체험단", "서울-맛집-체험단"],
  },
  {
    slug: "인스타체험단",
    title: "인스타 체험단 모집 모아보기",
    description: "인스타그램, 릴스, SNS 리뷰어를 모집하는 체험단 캠페인을 확인해보세요.",
    h1: "인스타 체험단 모집 모아보기",
    intro: "인스타그램 콘텐츠 제작이나 릴스 업로드가 필요한 캠페인을 빠르게 찾을 수 있습니다.",
    filters: { channelKeywords: ["인스타", "릴스"] },
    appQuery: "?tab=explore&preset=instagram",
    relatedSlugs: ["체험단", "뷰티체험단", "카페체험단"],
  },
  {
    slug: "맛집체험단",
    title: "맛집 체험단 모집 모아보기",
    description: "전국 맛집 체험단 캠페인을 지역, 마감일, 제공내역 기준으로 비교해보세요.",
    h1: "맛집 체험단 모집 모아보기",
    intro: "식사권, 메뉴 제공, 방문 리뷰 등 맛집 중심 캠페인을 한 번에 비교합니다.",
    filters: { categoryKeywords: ["맛집", "식품"] },
    appQuery: "?tab=explore&category=맛집",
    relatedSlugs: ["서울-맛집-체험단", "부산-맛집-체험단", "오늘마감-체험단"],
  },
  {
    slug: "카페체험단",
    title: "카페 체험단 모집 모아보기",
    description: "카페, 디저트, 음료 체험단 캠페인을 한 곳에서 찾아보세요.",
    h1: "카페 체험단 모집 모아보기",
    intro: "카페 방문, 디저트, 음료 제공 캠페인을 중심으로 최신 모집글을 정리합니다.",
    filters: { categoryKeywords: ["카페", "디저트"] },
    appQuery: "?tab=explore&category=카페",
    relatedSlugs: ["맛집체험단", "서울-맛집-체험단", "인스타체험단"],
  },
  {
    slug: "뷰티체험단",
    title: "뷰티 체험단 모집 모아보기",
    description: "뷰티, 피부관리, 헤어, 네일 관련 체험단 캠페인을 찾아보세요.",
    h1: "뷰티 체험단 모집 모아보기",
    intro: "뷰티 서비스와 제품 체험 캠페인을 지역과 마감일 기준으로 비교합니다.",
    filters: { categoryKeywords: ["뷰티", "미용", "헤어", "네일"] },
    appQuery: "?tab=explore&category=뷰티",
    relatedSlugs: ["체험단", "인스타체험단", "오늘마감-체험단"],
  },
  {
    slug: "서울-맛집-체험단",
    title: "서울 맛집 체험단 모집 모아보기",
    description: "서울 지역 맛집 체험단 캠페인을 마감일과 제공내역 기준으로 비교해보세요.",
    h1: "서울 맛집 체험단 모집 모아보기",
    intro: "서울에서 모집 중인 맛집 체험단을 중심으로 방문 위치, 마감일, 제공내역을 확인할 수 있습니다.",
    filters: { province: "서울", categoryKeywords: ["맛집", "식품"] },
    appQuery: "?tab=explore&province=서울&category=맛집",
    relatedSlugs: ["맛집체험단", "오늘마감-체험단", "블로그체험단"],
  },
  {
    slug: "부산-맛집-체험단",
    title: "부산 맛집 체험단 모집 모아보기",
    description: "부산 지역 맛집 체험단 캠페인을 마감일과 제공내역 기준으로 비교해보세요.",
    h1: "부산 맛집 체험단 모집 모아보기",
    intro: "부산에서 모집 중인 맛집 체험단을 중심으로 위치와 조건을 빠르게 살펴볼 수 있습니다.",
    filters: { province: "부산", categoryKeywords: ["맛집", "식품"] },
    appQuery: "?tab=explore&province=부산&category=맛집",
    relatedSlugs: ["맛집체험단", "서울-맛집-체험단", "오늘마감-체험단"],
  },
  {
    slug: "오늘마감-체험단",
    title: "오늘 마감 체험단 모집 모아보기",
    description: "오늘 또는 곧 마감되는 체험단 캠페인을 빠르게 확인해보세요.",
    h1: "오늘 마감 체험단 모집 모아보기",
    intro: "마감이 가까운 체험단 캠페인을 우선 확인하고 원문 신청 페이지로 이동할 수 있습니다.",
    filters: { maxDday: 1 },
    appQuery: "?tab=explore&preset=deadline",
    relatedSlugs: ["체험단", "맛집체험단", "서울-맛집-체험단"],
  },
  {
    slug: "디너의여왕-체험단",
    title: "디너의여왕 체험단 모집 모아보기",
    description: "디너의여왕 체험단 캠페인을 제공내역과 마감일 기준으로 확인해보세요.",
    h1: "디너의여왕 체험단 모집 모아보기",
    intro: "디너의여왕에 올라온 공개 캠페인을 제공내역과 함께 비교할 수 있습니다.",
    filters: { platformIds: ["dinner"] },
    appQuery: "?tab=explore&platform=dinner",
    relatedSlugs: ["체험단", "맛집체험단", "오늘마감-체험단"],
  },
  {
    slug: "레뷰-체험단",
    title: "레뷰 체험단 모집 모아보기",
    description: "레뷰에 올라온 맛집, 뷰티, 생활 체험단 모집 정보를 한 곳에서 비교해보세요.",
    h1: "레뷰 체험단 캠페인 모아보기",
    intro: "레뷰 공개 모집 캠페인을 마감일과 제공내역 중심으로 정리해 빠르게 비교할 수 있습니다.",
    filters: { platformIds: ["revu"] },
    appQuery: "?tab=explore&platform=revu",
    relatedSlugs: ["체험단", "오늘마감-체험단", "맛집체험단"],
  },
  {
    slug: "미블-체험단",
    title: "미블 체험단 모집 모아보기",
    description: "미블 체험단 캠페인을 맛집, 카페, 뷰티 등 관심 조건별로 확인해보세요.",
    h1: "미블 체험단 캠페인 모아보기",
    intro: "미블에 올라온 공개 모집 캠페인을 제공내역, 지역, 마감일 기준으로 비교합니다.",
    filters: { platformIds: ["mrblog"] },
    appQuery: "?tab=explore&platform=mrblog",
    relatedSlugs: ["체험단", "맛집체험단", "카페체험단"],
  },
  {
    slug: "강남-맛집-체험단",
    title: "강남 맛집 체험단 모집 모아보기",
    description: "강남 지역 맛집 체험단 모집 정보를 마감일과 제공내역 기준으로 비교해보세요.",
    h1: "강남 맛집 체험단 캠페인 모아보기",
    intro: "강남 키워드가 포함된 맛집 체험단 캠페인을 모아 방문 조건과 신청 흐름을 빠르게 확인합니다.",
    filters: { textKeywords: ["강남", ["맛집", "음식", "식품"]] },
    appQuery: "?tab=explore&query=강남%20맛집",
    relatedSlugs: ["맛집체험단", "서울-맛집-체험단", "오늘마감-체험단"],
  },
  {
    slug: "서울-블로그-체험단",
    title: "서울 블로그 체험단 모집 모아보기",
    description: "서울 지역 블로그 리뷰 체험단 캠페인을 한 곳에서 찾아보세요.",
    h1: "서울 블로그 체험단 캠페인 모아보기",
    intro: "서울 키워드와 블로그 리뷰 조건이 있는 체험단 캠페인을 중심으로 정리합니다.",
    filters: { textKeywords: ["서울", "블로그"] },
    appQuery: "?tab=explore&query=서울%20블로그",
    relatedSlugs: ["블로그체험단", "서울-맛집-체험단", "체험단"],
  },
  {
    slug: "부산-카페-체험단",
    title: "부산 카페 체험단 모집 모아보기",
    description: "부산 카페와 디저트 체험단 모집 정보를 조건별로 비교해보세요.",
    h1: "부산 카페 체험단 캠페인 모아보기",
    intro: "부산 지역 카페, 디저트 관련 체험단 캠페인을 마감일과 제공내역 기준으로 모았습니다.",
    filters: { textKeywords: ["부산", ["카페", "디저트"]] },
    appQuery: "?tab=explore&query=부산%20카페",
    relatedSlugs: ["카페체험단", "맛집체험단", "체험단"],
  },
  {
    slug: "뷰티-체험단-모집",
    title: "뷰티 체험단 모집 모아보기",
    description: "미용, 헤어, 네일 등 뷰티 체험단 모집 정보를 한 곳에서 비교해보세요.",
    h1: "뷰티 체험단 모집 캠페인 모아보기",
    intro: "뷰티 서비스와 제품 체험단 캠페인을 제공내역, 지역, 마감일 기준으로 확인합니다.",
    filters: { textKeywords: [["뷰티", "미용", "헤어", "네일"]] },
    appQuery: "?tab=explore&category=뷰티",
    relatedSlugs: ["체험단", "인스타체험단", "오늘마감-체험단"],
  },
  {
    slug: "오늘마감-블로그-체험단",
    title: "오늘 마감 블로그 체험단 모집 모아보기",
    description: "오늘 또는 곧 마감되는 블로그 체험단 캠페인을 빠르게 확인해보세요.",
    h1: "오늘 마감 블로그 체험단 캠페인 모아보기",
    intro: "마감이 가까운 블로그 리뷰 체험단 캠페인을 우선 정리해 신청 기회를 놓치지 않도록 돕습니다.",
    filters: { maxDday: 1, textKeywords: ["블로그"] },
    appQuery: "?tab=explore&preset=deadline&query=블로그",
    relatedSlugs: ["오늘마감-체험단", "블로그체험단", "체험단"],
  },
  {
    slug: "배송형-체험단",
    title: "배송형 체험단 모집 모아보기",
    description: "방문 없이 상품을 받아 리뷰하는 배송형 체험단 캠페인을 제공내역과 마감일 기준으로 비교해보세요.",
    h1: "배송형 체험단 모집 모아보기",
    intro: "택배로 상품을 받아 체험하는 캠페인을 중심으로 마감일, 제공내역, 신청 흐름을 빠르게 확인합니다.",
    filters: { campaignTypes: ["delivery", "배송형"] },
    appQuery: "?tab=explore&type=delivery",
    relatedSlugs: ["제품-체험단", "블로그체험단", "오늘마감-체험단"],
  },
  {
    slug: "제품-체험단",
    title: "제품 체험단 모집 모아보기",
    description: "생활용품, 뷰티, 식품 등 제품 제공형 체험단 캠페인을 한 곳에서 비교해보세요.",
    h1: "제품 체험단 모집 모아보기",
    intro: "제품을 받아 사용해보고 리뷰하는 캠페인을 제공내역, 모집 인원, 마감일 기준으로 정리합니다.",
    filters: {
      campaignTypes: ["delivery", "배송형"],
      textKeywords: [["제품", "상품", "생활용품", "화장품", "식품", "뷰티", "패션", "건강", "생활", "주방", "육아"]],
    },
    appQuery: "?tab=explore&type=delivery",
    relatedSlugs: ["배송형-체험단", "뷰티체험단", "오늘마감-체험단"],
  },
];

export function getLandingPage(slug) {
  return SEO_LANDING_PAGES.find((page) => page.slug === decodeURIComponent(String(slug || ""))) || null;
}
