from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from quantum_trainer.filing_text_scan import run_opendart_text_risk_scan
from quantum_trainer.opendart_client import load_opendart_api_key

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download selected OpenDART filing documents and scan risk-review keyword evidence."
    )
    parser.add_argument("--symbol", default="028260.KS", help="Ticker symbol to scan.")
    parser.add_argument(
        "--disclosures-csv",
        default=str(PROJECT_ROOT / "reports" / "filing_review" / "opendart_filings_028260.csv"),
        help="OpenDART disclosure list CSV generated by fetch_opendart_filing_review.py.",
    )
    parser.add_argument(
        "--max-documents",
        type=int,
        default=2,
        help="Maximum annual/quarterly/semiannual filings to download.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(PROJECT_ROOT / "reports"),
        help="Output reports root.",
    )
    parser.add_argument(
        "--env",
        default=str(PROJECT_ROOT / ".env"),
        help="Path to local .env file containing OPENDART_API_KEY.",
    )
    return parser.parse_args()


def main() -> int:
    try:
        args = parse_args()
        api_key = load_opendart_api_key(args.env)
        output = run_opendart_text_risk_scan(
            symbol=args.symbol,
            disclosures_csv=Path(args.disclosures_csv),
            api_key=api_key,
            output_dir=Path(args.output_dir),
            max_documents=args.max_documents,
        )
        logger.info("OpenDART text risk scan complete.")
        logger.info("Evidence CSV: %s", output.evidence_csv_path)
        logger.info("Summary CSV: %s", output.summary_csv_path)
        logger.info("Markdown report: %s", output.markdown_path)
        print(f"evidence_csv={output.evidence_csv_path}")
        print(f"summary_csv={output.summary_csv_path}")
        print(f"markdown_report={output.markdown_path}")
        print(f"document_count={output.summary['document_count']}")
        print(f"evidence_count={output.summary['evidence_count']}")
        print(output.summary_report.to_string(index=False))
        return 0
    except FileNotFoundError as exc:
        logger.error("%s", exc)
        return 2
    except Exception as exc:
        logger.exception("OpenDART text risk scan failed: %s", exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
